netmesh_rfc6349_app/device_registration/routes.py
import json
import re
import requests

from flask import Blueprint, request, render_template, redirect, url_for, session, current_app, jsonify

from netmesh_rfc6349_app.device_registration.utils import get_device_info
from netmesh_rfc6349_app.main.utils import netmesh_location
from netmesh_rfc6349_app.main.utils.netmesh_config_file import NetMeshConfigFile

device_registration = Blueprint('device_registration', __name__)


@device_registration.route('/register-api', methods=['POST'])
def register_api():
    admin_email = request.form.get('adminEmail')
    device_owner_info = json.loads(request.form.get('deviceOwnerInfo'))
    device_name = request.form.get('deviceName')

    try:
        device_info = get_device_info()
        device_info.update({"name": device_name})
        device_info.update({"owner": device_owner_info['user_id']})

        req = requests.post(
            url=f"{current_app.config['RESULTS_SERVER_API_URI']}/rfc6349/device/",
            headers={"Authorization": f"Token {session['admin-token']}"},
            json=device_info
        )
        print(device_info)
        req.raise_for_status()

        config = NetMeshConfigFile()

        # device_config = config.load_device_config()
        config.device_config.set_device_name(device_name)
        config.device_config.set_device_nro_id(session['admin-nro-id'])

        config.users_config.set_logged_user({
            "name": device_owner_info['name'],
            "email": device_owner_info['email'],
        })

        config.save()
        
        session['admin-token'] = None
        session['admin-nro-id'] = None
        session['admin-ntc-region-name'] = None

        return jsonify(html=render_template('device_registration_done.html',
                               device_name=device_name,
                               admin_email=admin_email,
                               device_info=get_device_info())), 200
    except requests.exceptions.HTTPError as ex:
        print("http", ex.response.text)
        error = ""
        print(ex.response.status_code)
        try:
            error_json = json.loads(req.text)
            if "detail" in error_json:
                error = error_json["detail"]
            else:
                error = str(ex)
        except ValueError:
            error = str(ex)
            
        return jsonify(error=error), 400
    except requests.exceptions.ConnectionError as e:
        return jsonify(error="Connection error. Please check your Internet, and try again."), 500
    except requests.exceptions.RequestException as ex:
        print(ex)
        return jsonify(error=str(ex)), 400
    except Exception as ex:
        print("ex", ex)
        return jsonify(error=str(ex)), 400


@device_registration.route('/register-device')
def register_device_page():
    session['admin-token'] = None

    config = NetMeshConfigFile()
    # device_config = config.load_device_config()

    device_name = config.device_config.get_device_name()
    nro_id = config.device_config.get_device_nro_id()
    if device_name and nro_id:
        return redirect(url_for('users.login_page'))

    return render_template('register_device.html',
                           device_info=get_device_info())


@device_registration.route('/get-admin-credentials-template', methods=['POST'])
def get_admin_credentials_template():
    return render_template('device_admin_credentials.html')


@device_registration.route('/log-admin', methods=['POST'])
def log_admin():
    # device_name = request.form.get('device-name')
    admin_email = request.form.get('admin-email')
    admin_password = request.form.get('admin-password')

    # print(admin_email, admin_password)

    r = None
    users_response = []
    try:
        r = requests.post(
            url=f"{current_app.config['RESULTS_SERVER_API_URI']}/user/token/",
            json={
                "email": admin_email,
                "password": admin_password,
                "client": "admin"
            }
        )
        r.raise_for_status()

        admin_response = r.json()
        print(admin_response)

        token = admin_response['token']
        # ntc_region = admin_response['user']['nro']['region']
        # ntc_regions = dict(netmesh_location.get_philippine_regions())

        # print("ntc_region", ntc_region)

        session['admin-token'] = token
        session['admin-nro-id'] = str(admin_response['user']['nro']['id'])
        session['admin-ntc-region-name'] = admin_response['user']['nro']['description']
        print(session['admin-ntc-region-name'])

        r = requests.get(
            url=f"{current_app.config['RESULTS_SERVER_API_URI']}/user/manage/",
            params={
                "nro": session['admin-nro-id']
            },
            headers={'Authorization': f"Token { session['admin-token'] }"}
        )
        r.raise_for_status()

        users_response = r.json()
    except requests.exceptions.HTTPError as ex:
        print(ex)
        print("HTTP error")
        error = "Unexpected error"
        try:
            error_json = json.loads(r.content)
            if ex.response.status_code == 400:
                error = "Invalid email or password"
            elif "non_field_errors" in error_json:
                error = error_json["non_field_errors"]
            else:
                error = r.content
        except Exception as ex2:
            print(ex or ex2)
            error = str(ex or ex2)
            
        return render_template('device_admin_credentials.html', error=error, admin_email=admin_email, admin_password=admin_password), 400
    except requests.exceptions.ConnectionError as ex:
        print(ex)
        print(ex.strerror)
        return render_template('device_admin_credentials.html', error=str(ex), admin_email=admin_email, admin_password=admin_password), 400
    except requests.exceptions.RequestException as ex:
        print(ex.response)
        

        return render_template('device_admin_credentials.html', error=str(ex), admin_email=admin_email, admin_password=admin_password), 400

    return render_template('device_details_form.html', region_name=session['admin-ntc-region-name'], users=users_response)


# @device_registration.route('/get-device-details-template', methods=['POST'])
# def get_device_details_template():
#     nro_id = session['admin-nro-id']
#     region_name = session['admin-ntc-region-name']

#     # print("ntc_region", region)
#     print("token", session['admin-token'])

#     # regions = netmesh_location.get_philippine_regions()
#     try:
#         r = requests.get(
#             url=f"{current_app.config['RESULTS_SERVER_API_URI']}/user/manage/",
#             params={
#                 "nro": nro_id
#             },
#             headers={'Authorization': f"Token { session['admin-token'] }"}
#         )
#         r.raise_for_status()

#         print("users")
#         print(r.text)
#     except requests.exceptions.RequestException as re:
#         error = "Unexpected error"
#         try:
#             error_json = json.loads(r.content)
#             if "non_field_errors" in error_json:
#                 error = error_json["non_field_errors"]
#             else:
#                 error = r.content
#         except Exception as ex:
#             print(ex)
#             error = str(re)

#         # TODO: show error on modal admin credentials
#         return render_template('device_details_form.html', error=error), 400

#     return render_template('device_details_form.html', users=r.json(), region_name=region_name)


@device_registration.route('/device-confirmation-template', methods=['POST'])
def device_confirmation_template():
    region_name = session['admin-ntc-region-name']
    laptop_owner = request.form.get('laptopOwner')
    laptop_owner_email = request.form.get('laptopOwnerEmail')
    laptop_name = request.form.get('laptopName')

    return render_template('device_confirmation.html',
                           region_name=region_name,
                           laptop_owner=laptop_owner,
                           laptop_name=laptop_name,
                           laptop_owner_email=laptop_owner_email,
                           device_info=get_device_info())


@device_registration.route('/reset-registration', methods=['POST'])
def reset_registration():
    ini = NetMeshConfigFile()
    try:
        ini.delete()
        return jsonify(), 200
    except Exception as ex:
        return jsonify(error=str(ex)), 400

netmesh_rfc6349_app/users/routes.py
import requests
import json

from flask import Blueprint, Response, redirect, request, render_template, jsonify, session, url_for, current_app

from netmesh_rfc6349_app.main.utils.netmesh_config_file import NetMeshConfigFile
from netmesh_rfc6349_app.main.utils.laptop_info import get_ubuntu_version
from netmesh_rfc6349_app.main.utils.netmesh_installer import get_app_current_version
from netmesh_rfc6349_app.main.utils import log_settings

from netmesh_rfc6349_app.users import utils

users = Blueprint('users', __name__)


@users.route('/login')
def login_page():
    config = NetMeshConfigFile()
    # device_config = config.load_device_config()
    # users_config = config.load_users_config()
    
    device_name = config.device_config.get_device_name()
    nro_id = config.device_config.get_device_nro_id()
    if not device_name or not nro_id:
        return redirect(url_for('device_registration.register_device_page'))
    
    return render_template('login.html',
                           logged_users=config.users_config.get_logged_users(),
                           app_version=get_app_current_version(),
                           ubuntu_version=get_ubuntu_version(),
                           device_name=device_name)


@users.route('/check-user-token', methods=['POST'])
def check_user_token():
    user_email = request.form.get("email")
    
    config = NetMeshConfigFile()
    logging_user = config.users_config.get_logged_user(user_email)
    
    if 'token' in logging_user:
        token = logging_user['token']
        try:
            req = requests.get(url=f"{current_app.config['RESULTS_SERVER_API_URI']}/user/myprofile/",
                                headers={
                                    'Authorization': f'Token {token}'
                                })
            req.raise_for_status()
            
            res = req.json()
            utils.save_logged_user(token,
                                   res['email'],
                                   res['first_name'],
                                   res['last_name'],
                                   logging_user['token_expiry'])
            
            return jsonify(url=url_for('main.home_page'), info='Success'), 200
        except requests.exceptions.RequestException as re:
            error = ''
            try:
                error_json = req.json()
                if "detail" in error_json:
                    error = error_json["detail"]
                else:
                    error = json.dumps(error_json)
            except Exception as ex:
                error = re.response.text
                
            return jsonify(url=None, info=error), re.response.status_code
    else:
        return jsonify(url=None, info='User not logged in yet'), 200


@users.route('/login-submit', methods=['POST'])
def login():
    session.permanent = True
    
    user_email = request.form.get("user-email")
    password = request.form.get("user-password")

    print(user_email, password)

    error = None
    try:
        data = utils.login(user_email, password)
        
        utils.save_logged_user(data['token'],
                               data['user']['email'],
                               data['user']['first_name'],
                               data['user']['last_name'],
                               data['expiry'])
        
        return jsonify(goto=url_for('main.home_page')), 200
    except requests.exceptions.ConnectionError as ex:
        return jsonify(error="Connection error. Please check your Internet connection"), 400
    except requests.exceptions.Timeout as ex:
        return jsonify(error="Connection timeout. Please try again"), 400
    except requests.exceptions.RequestException as ex:
        error_content = "Unexpected error occured"
        try:
            error_content = ex.response.content
            error_json = json.loads(error_content)
            if ex.response.status_code == 400:
                return jsonify(error="Invalid email or password"), 400
            if error_json and "non_field_errors" in error_json:
                return jsonify(error=error_json["non_field_errors"]), 400
            else:
                return jsonify(error=str(error_content)), 400
        except Exception:
            return jsonify(error=str(error_content)), 400
    except Exception as e:
        print("error", e)
        return jsonify(error=str(e)), 500

@users.route('/refresh-logged-users', methods=['POST'])
def refresh():
    user_email = request.form.get("email")
    
    config = NetMeshConfigFile()
    config.users_config.remove_logged_user(user_email)
    config.save()
    
    return jsonify(url=url_for('users.login_page'))

@users.route('/relogin', methods=['POST'])
def relogin():
    email = session['email']
    password = request.form.get("password")

    print(email)
    print(password)

    error = None
    try:
        token = utils.relogin(email, password)
        session['api_session_token'] = token
        session['email'] = email
    except requests.exceptions.ConnectionError as ce:
        error = "Connection error. Please check your Internet connection"
    except requests.exceptions.Timeout as te:
        error = "Connection timeout. Please try again"
    except requests.exceptions.RequestException as req:
        error = "Cannot login\n" + str(req)
    except Exception as e:
        error = str(e)

    if error is None:
        return Response(json.dumps({}), 200)
    else:
        print("oh no")
        log_settings.log_error(error)
        return Response(json.dumps({
            "error": error
        }), 500)


@users.route('/logout')
def logout():
    # config_file = NetMeshConfigFile()
    
    # user = config_file.users_config.get_logged_user(session['email'])
    # if user:
    #     config_file.users_config.set_logged_user({
    #         "name": user['name'],
    #         "email": session['email']
    #     })
    #     config_file.save()

    session['api_session_token'] = None
    session['email'] = None
    session['name'] = None
    
    # return redirect(url_for('users.login_page'))
    return url_for('users.login_page')

netmesh_rfc6349_app/templates/base.html
<!doctype html>
<html lang="en">
  {% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="preload" as="image" href="../static/images/netmesh-icon.webp">
    <link rel="preload" as="image" href="../static/images/netmesh-logo.webp">
    <style>
      .loading-page {
        position: fixed;
        width: 100vw;
        height: 100vh;
        top: 0;
        left: 0;
        z-index: 2000;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }

      body {
        overflow: hidden;
      }

      @keyframes fade {
        from {
          visibility: collapse;
          opacity: 0;
        }
        to {
          visibility: visible;
          opacity: 1;
        }
      }
      .fade-out {
        animation: fade reverse 100ms ease-out forwards;
      }

      @keyframes glow {
        from {
          filter: brightness(1) opacity(1)
        }
        to {
          filter: brightness(1.33) opacity(0.33)
        }
      }
      .glow {
        animation: glow 750ms ease-in-out infinite alternate;
      }
    </style>

    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    
    <script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/bootstrap-icons/font/bootstrap-icons.css') }}">

    <script src="{{ url_for('static', filename='node_modules/select2/dist/js/select2.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/select2/dist/css/select2.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/select2-bootstrap-5-theme/dist/select2-bootstrap-5-theme.min.css') }}">

    <script src="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet-image/leaflet-image.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.css') }}">

    <script src="{{ url_for('static', filename='node_modules/apexcharts/dist/apexcharts.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/apexcharts/dist/apexcharts.css') }}" />
    
    <script src="{{ url_for('static', filename='node_modules/moment/min/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/numeral/min/numeral.min.js') }}"></script>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" />

  {% endblock %}

  {% block body %}

  <div id="loading-page" class="loading-page bg-body">
    <img src="../static/images/netmesh-icon.webp" class="glow" width="144" height="auto" />
  </div>
  
  {% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/global.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/tooltip.js') }}"></script>

    <script>
      (function () {
        window.onload = function () {
          document.getElementById('loading-page')?.classList.add('fade-out');
          document.body.style.overflow = 'auto';
        }
      })();
    </script>
  {% endblock scripts %}

  {% endblock body %}
</html>

netmesh_rfc6349_app/templates/device_admin_credentials.html
<div class="mb-3">
  <label class="form-label mb-1" for="admin-email">Admin email</label>
  <input
    id="admin-email"
    name="admin-email"
    type="email"
    class="form-control mb-2"
    placeholder="Enter admin email"
    value="{{ admin_email }}"
    required
  />
</div>
<div class="mb-3">
  <label class="form-label mb-1" for="admin-password">Admin password</label>
  <div class="input-group input-group">
    <input
      id="admin-password"
      name="admin-password"
      type="password"
      class="form-control"
      placeholder="Enter admin password"
      value="{{ admin_password }}"
      required />	
    <input
      type="checkbox"
      class="btn-check"
      id="admin-password-eye"
      autocomplete="off">
    <label
      class="btn btn-outline-secondary"
      for="admin-password-eye">
      <i class="bi bi-eye"></i>
    </label>
  </div>
</div>
{% if error %}
<div class="alert alert-danger alert-dismissible fade show overflow-auto py-1 small" role="alert">
  {{ error }}
</div>
{% endif %}
<script>
  (function () {
    $('#admin-password-eye').on('change', function () {
      if (this.checked) {
        $('#admin-password').attr('type', 'text');
      } else {
        $('#admin-password').attr('type', 'password');
      }
    });
  })();
</script>

netmesh_rfc6349_app/templates/device_confirmation.html
<h6 class="mb-1">Please check the following information you've entered:</h6>
<div class="card mb-3 border-primary">
  <div class="card-body px-2 py-1 pb-2">
    <div class="row gx-2 gy-0">
      <div class="col-sm-3">
        <span class="small text-primary">Region</span>
      </div>
      <div class="col-sm-9">
        <span class="small fw-bold">
          {{ region_name }}
        </span> 
      </div>

      <div class="col-sm-3">
        <span class="small text-primary">Laptop owner</span>
      </div>
      <div class="col-sm-9">
        <div class="small fw-bold">
          <div class="">{{ laptop_owner }}</div>
          <div class="text-secondary">{{ laptop_owner_email }}</div>
        </div>
      </div>

      <div class="col-sm-3">
        <span class="small text-primary">Laptop name</span>
      </div>
      <div class="col-sm-9">
        <span class="small fw-bold">
          {{ laptop_name }}
        </span> 
      </div>
    </div>
  </div>
</div>
<label class="mb-1 fw-bold text-secondary small">Device info</label>
{% include 'device_info.html' %}

netmesh_rfc6349_app/templates/register_device.html
{% extends 'base.html' %}

{% block head %}
	{{ super() }}
	<title>Device Registration</title>
	<style>
		div.alert-danger {
			max-height: 73px;
		}

		.main-content {
			width: 480px;
		}
		
		.registration-form {
			height: 400px;
		}
		
		.carousel-inner .carousel-item {
			transition: -webkit-transform 0.3s ease;
			transition: transform 0.3s ease;
			transition: transform 0.3s ease, -webkit-transform 0.3s ease;
		}
	</style>
{% endblock %}

{% block body %}

<div class="d-flex justify-content-center align-items-center vh-100">
	<div class="main-content border rounded p-4">
		<div class="d-flex mb-3">
			<img
				class="me-3"
				src="{{url_for('static', filename='images/netmesh-logo.webp')}}"
				width="70"
				height="100%"
			/>
			<div class="fill-flex align-self-center">
				<h4 class="mb-0">
					{{ config['APP_TITLE'] }}
					<div class="small">Laptop Registration</div>
				</h4>
			</div>
		</div>
		<div id="carousel-registration" class="carousel slide" data-bs-ride="false" data-bs-touch="false" data-bs-interval="false" data-bs-wrap="false">
			<div class="carousel-inner">
				<div class="carousel-item p-2 active">
					<div class="d-flex flex-column registration-form">
						<div id="welcome-device-content">
							{% include 'device_registration_welcome.html' %}
						</div>
						<div class="mt-auto">
							<div class="d-flex justify-content-end">
								<!-- <button id="already-registered-button" type="button" class="btn btn-sm btn-link me-auto">Already registered this device</button> -->
								<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#admin-credentials-modal">Start Registration</button>
							</div>
						</div>
					</div>
				</div>
				<!-- <div class="carousel-item p-2">
					<div class="d-flex flex-column registration-form">
						<div id="ntc-region-selection-content">
						</div>
						<div class="mt-auto">
							<div class="d-flex justify-content-end">
								<button id="submit-region-button" type="button" class="btn btn-primary">Continue</button>
							</div>
						</div>
					</div>
				</div> -->
				<div class="carousel-item p-2">
					<div class="d-flex flex-column registration-form">
						<div id="device-details-content">
						</div>
						<div class="mt-auto">
							<div class="d-flex justify-content-end">
								<!-- <button type="button" class="btn btn-sm btn-link link-danger p-0 me-auto">Cancel registration</button> -->
								<div class="me-auto">
									<button class="btn btn-outline-secondary btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="bi bi-three-dots-vertical"></i>
										Options
									</button>
									<ul class="dropdown-menu">
										<li>
											<a id="cancel-registration-button" href="#" class="dropdown-item small">
												<span class="text-danger">Cancel registration</span>
											</a>
										</li>
									</ul>
								</div>
								<button id="device-confirmation-button" type="button" class="btn btn-primary" disabled="true">Continue</button>
							</div>
						</div>
					</div>
				</div>
				<div class="carousel-item p-2">
					<div class="d-flex flex-column registration-form">
						<div id="device-registered-content">
							
						</div>
						<div class="mt-auto">
							<div class="d-flex justify-content-end">
								<a id="use-rfc-button" href="/" class="btn btn-primary">Use {{ config['APP_TITLE'] }}</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="admin-credentials-modal" class="modal" tabindex="-1" data-bs-keyboard="true" data-bs-backdrop="static" aria-labelledby="admin-credentials-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <form class="modal-content" action="{{ url_for('device_registration.log_admin') }}" method="POST">
      <div class="modal-header">
        <h5 class="modal-title">Enter admin credentials</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
				{% include 'device_admin_credentials.html' %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">
					<div class="spinner-border spinner-border-sm" role="status" hidden>
						<span class="visually-hidden">Loading...</span>
					</div>
					Proceed
				</button>
      </div>
    </form>
  </div>
</div>

<div id="device-confirmation-modal" class="modal" tabindex="-1" data-bs-keyboard="true" data-bs-backdrop="static" aria-labelledby="device-confirmation-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <form class="modal-content" action="{{ url_for('device_registration.register_api') }}" method="POST">
      <div class="modal-header">
        <h5 class="modal-title">Laptop to register</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Register</button>
      </div>
    </form>
  </div>
</div>

{% block scripts %}
	<script>
		(function() {
			$(function () {
				const $registrationCarousel = $('#carousel-registration');

				let adminCredentailsAjax;
				const $adminCredentailsModal = $('#admin-credentials-modal');
				const $adminCredentailsForm = $('#admin-credentials-modal form');
				$adminCredentailsForm.on('submit', function (ev) {
					ev.preventDefault();

					const formData = new FormData(ev.target);

					$('.alert').remove();
					$('#admin-credentials-modal input, #admin-credentials-modal button:not(.btn-close)').attr('disabled', true);
					$('#admin-credentials-modal button .spinner-border').attr('hidden', false);

					adminCredentailsAjax = $.ajax({
						url: $adminCredentailsForm.attr('action'),
						method: $adminCredentailsForm.attr('method'),
						dataType: 'html',
						data: Object.fromEntries([...formData]),
						success: function (response) {
							$('#device-details-content').html(response);

							$registrationCarousel.carousel('next');
							
							$adminCredentailsModal.modal('hide');
						},
						error: function (jqXHR, textStatus, errorThrown) {
							console.log({jqXHR, textStatus, errorThrown});
							$('#admin-credentials-modal .modal-body').html(jqXHR.responseText);
						},
						complete: function (jqXHR, textStatus) {
							$('#admin-credentials-modal input, #admin-credentials-modal button:not(.btn-close)').attr('disabled', false);
							$('#admin-credentials-modal button .spinner-border').attr('hidden', true);
						}
					})
				});
				
				$adminCredentailsModal.on('show.bs.modal', function (ev) {
					$('.alert').remove();
					$('#admin-password').attr('type', 'password');
					$adminCredentailsForm.trigger("reset");
				});

				$adminCredentailsModal.on('hide.bs.modal', function (ev) {
					adminCredentailsAjax?.abort();
				});

				$adminCredentailsModal.on('shown.bs.modal', function (ev) {
					$('#admin-email').focus();
				});


				// const $submitRegionButton = $('#submit-region-button');
				// $submitRegionButton.on('click', function (ev) {
				// 	const ntcRegions = document.getElementById('ntc-region');

				// 	$.ajax({
				// 		url: 'get-device-details-template',
				// 		method: 'POST',
				// 		dataType: 'html',
				// 		data: {
				// 			region: ntcRegions.value,
				// 			regionName: $('#ntc-region option:selected').text()
				// 		},
				// 		success: function (response) {
				// 			$('#device-details-content').html(response);
							
				// 			$registrationCarousel.carousel('next');
				// 		},
				// 		error: function (jqXHR, textStatus, errorThrown) {
				// 			$('#ntc-region-selection-content').html(jqXHR.responseText);
				// 		}
				// 	});
				// });

				$('#cancel-registration-button').on('click', function (ev) {
					const willCancelRegistration = confirm("Do you want to cancel registration?");
					if (willCancelRegistration) {
						// $('#admin-credentials-modal .modal-body').load('device_admin_credentials.html');

						$registrationCarousel.carousel(0);
						$('#device-details-content').html("");
					}
				});

				const $deviceConfirmationModal = $('#device-confirmation-modal');
				$('#device-confirmation-button').on('click', function (ev) {
					const selectedOwner = $('#device-owner').select2('data')[0];
					console.log("selectedOwner", selectedOwner);

					if (selectedOwner.id) {
						document.getElementById('device-owner').classList.remove('is-invalid');
					} else {
						document.getElementById('device-owner').classList.add('is-invalid');
					}

					const laptopName = $('#device-name').data('name');
					if (laptopName) {
						document.getElementById('device-name').classList.remove('is-invalid');
					} else {
						document.getElementById('device-name').classList.add('is-invalid');
					}

					const isValid = document.getElementsByClassName('is-invalid').length === 0;
					if (!isValid) {
						return;
					}

					$.ajax({
						url: 'device-confirmation-template',
						method: 'POST',
						dataType: 'html',
						data: {
							// regionName: $('#ntc-region option:selected').text(),
							laptopOwner: `${$('#device-owner option:selected').text()}`,
							laptopOwnerEmail: selectedOwner.email,
							laptopName: laptopName
						},
						success: function (response) {
							console.log(response);
							$deviceConfirmationModal.modal('show');
							$('#device-confirmation-modal .modal-body').html(response);
						},
						error: function (jqXHR, textStatus, errorThrown) {
							console.error({jqXHR, textStatus, errorThrown});
							// $('#ntc-region-selection-content').html(jqXHR.responseText);
						}
					});
				});

				$('#device-confirmation-modal .modal-content').on('submit', function (ev) {
					ev.preventDefault();

					const selectedOwner = $('#device-owner').select2('data')[0];
					$.ajax({
						url: 'register-api',
						method: 'POST',
						dataType: 'json',
						data: {
							adminEmail: $('#admin-email').val(),
							deviceOwnerInfo: JSON.stringify({
								user_id: selectedOwner.id,
								name: selectedOwner.text,
								email: selectedOwner.email
							}),
							deviceName: $('#device-name').data('name')
						},
						success: function (response) {
							$deviceConfirmationModal.modal('hide');
							
							$('#device-registered-content').html(response.html);
							
							$registrationCarousel.carousel('next');
						},
						error: function (jqXHR, textStatus, errorThrown) {
							alert(jqXHR.responseJSON?.error ?? "Unknown error occured");
							console.error({jqXHR, textStatus, errorThrown});
							// $('#ntc-region-selection-content').html(jqXHR.responseText);
						}
					});
				});
			});
		})();
	</script>
{% endblock scripts %}

{% endblock body %}